---
abstract: 'module for discrete-event simulation'
author:
  - 'Pavel Shaydo, C<< <zwon at cpan.org> >>'
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Math::Random: 0
  Test::More: 0.63
  Test::Most: 0
  Test::use::ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simulation-DiscreteEvent
no_index:
  directory:
    - inc
    - t
requires:
  Module::Load: 0
  Moose: 0
  MooseX::MethodAttributes: 0.19
  namespace::clean: 0.13
resources:
  homepage: http://github.com/trinitum/perl-Simulation-DiscreteEvent/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-Simulation-DiscreteEvent.git
version: 0.09
