---
abstract: 'module for discrete-event simulation'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.63
  Test::use::ok: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simulation-DiscreteEvent
no_index:
  directory:
    - inc
    - t
requires:
  Module::Load: 0
  Moose: 0
  MooseX::MethodAttributes: 0.19
  namespace::clean: 0.13
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
